export const hashtagBodyClassMap = {
    a: 'hashtagBodyWork',
    b: 'hashtagBodyWork',
    c: 'hashtagBodyWork',
    d: 'hashtagBodyWork',
    e: 'hashtagBodyWork',
    f: 'hashtagBodyFriends',
    g: 'hashtagBodyFriends',
    h: 'hashtagBodyFriends',
    i: 'hashtagBodyFriends',
    j: 'hashtagBodyFriends',
    k: 'hashtagBodyHome',
    l: 'hashtagBodyHome',
    m: 'hashtagBodyHome',
    n: 'hashtagBodyHome',
    o: 'hashtagBodyHome',
    p: 'hashtagBodyA',
    q: 'hashtagBodyA',
    r: 'hashtagBodyA',
    s: 'hashtagBodyA',
    t: 'hashtagBodyA',
    u: 'hashtagBodyB',
    v: 'hashtagBodyB',
    w: 'hashtagBodyB',
    x: 'hashtagBodyB',
    y: 'hashtagBodyB',
    z: 'hashtagBodyB'
  };
  
  export const hashtagTextClassMap = {
    a: 'hashtagTextWork',
    b: 'hashtagTextWork',
    c: 'hashtagTextWork',
    d: 'hashtagTextWork',
    e: 'hashtagTextWork',
    f: 'hashtagTextFriends',
    g: 'hashtagTextFriends',
    h: 'hashtagTextFriends',
    i: 'hashtagTextFriends',
    j: 'hashtagTextFriends',
    k: 'hashtagTextHome',
    l: 'hashtagTextHome',
    m: 'hashtagTextHome',
    n: 'hashtagTextHome',
    o: 'hashtagTextHome',
    p: 'hashtagTextA',
    q: 'hashtagTextA',
    r: 'hashtagTextA',
    s: 'hashtagTextA',
    t: 'hashtagTextA',
    u: 'hashtagTextB',
    v: 'hashtagTextB',
    w: 'hashtagTextB',
    x: 'hashtagTextB',
    y: 'hashtagTextB',
    z: 'hashtagTextB'
  };